sudo: required
services:
    - docker

before_install:
    - docker build -t snehasish4/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true snehasish4/react-test npm test

after_success:
    - docker build -t snehasish4/multi-client ./client
    - docker build -t snehasish4/multi-nginx ./nginx
    - docker build -t snehasish4/multi-server ./server
    - docker build -t snehasish4/multi-worker ./worker
    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take the images and push them to docker hub
    - docker push snehasish4/multi-client
    - docker push snehasish4/multi-nginx
    - docker push snehasish4/multi-server
    - docker push snehasish4/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker-prod
    env: MultiDockerProd-env
    bucket_name: elasticbeanstalk-us-east-2-705894028972
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY